In [1]:
import fastText

In [2]:
fasttext = fastText.load_model('fasttext.bin')


In [3]:
import pandas as pd
import numpy as np
from progressbar import progressbar as pb

df = pd.read_csv('all_data_fixed3.csv')

In [4]:
print(len(df))
df.head()

5330


0  \
0   Совещательный орган при императоре в начале XX в   
1  Министр внутренних дел с 1904 г либерал автор ...   
2  Какое из названных событий произошло 27 января...   
3  Что из названного относится к результатам перв...   
4  Для выхода из экономического кризиса вызванног...   

                                               1  \
0                                          Сенат   
1                                  Лорис Меликов   
2      подрыв флагманского корабля Петропавловск   
3                     появление многопартийности   
4  ввело 8 часовой рабочий день в промышленности   

                                                  2  \
0                             Государственный совет   
1                                 Святополк Мирский   
2  высадка японских войск на Ляодунском полуострове   
3             формирование конституционной монархии   
4             ликвидировало помещичье землевладение   

                                  3  \
0                Консилия министров   
1                           Милюков   
2  героический бой Варяга и Корейца   
3       ликвидация сословного строя   
4         отменило выкупные платежи   

                                             4  5  
0                       Верховный тайный совет  2  
1                                        Витте  2  
2    заключение Портсмутского мирного договора  3  
3  введение рабочего контроля за производством  1  
4           ввело продовольственную разверстку  4

In [5]:
lst_df = df.values.tolist()
lst_df[0]

['Совещательный орган при императоре в начале XX в',
 'Сенат',
 'Государственный совет',
 'Консилия министров',
 'Верховный тайный совет',
 2]

In [6]:
def get_vec(lst):
    res = np.zeros((5,300))
    for i in range(len(lst)-1):
        cur_vec = np.zeros(300)
        cur_tag = lst[i].split(' ')
        for c in cur_tag:
            try:
                cur_vec += fasttext.get_word_vector(c)
            except:
                continue
        res[i,:] = cur_vec
    return res

In [7]:
from multiprocessing import Pool

p = Pool(6)

FT_embs = p.map(get_vec, lst_df)
FT_embs = np.array(FT_embs)

In [8]:
import pickle

with open('fasttext_embed3.pickle', 'wb') as f:
    pickle.dump(FT_embs, f)

In [9]:
from sklearn.metrics.pairwise import cosine_similarity as cos
cosines = np.zeros((FT_embs.shape[0], FT_embs.shape[1]-1))
cosines.shape

(5330, 4)

In [10]:
for i in range(len(df)):
    for j in range(1,5):
        cosines[i, j-1] = cos(FT_embs[i,0].reshape(1,-1), FT_embs[i,j].reshape(1,-1))[0]

In [11]:
cosines

array([[ 0.19440531,  0.17442491, -0.01326479,  0.19964368],
       [ 0.18635438,  0.16732294,  0.26197196,  0.24486485],
       [ 0.20581724,  0.33038647,  0.20055023,  0.17308868],
       ...,
       [ 0.25240314,  0.34019593,  0.35046837,  0.34019593],
       [ 0.27919196,  0.15199645,  0.17402604,  0.21909671],
       [ 0.13518369,  0.186899  ,  0.12405629,  0.12276438]])

In [12]:
preds = np.argmax(cosines, axis=1)
preds = preds + 1
preds

array([4, 3, 2, ..., 3, 1, 2])

In [13]:
target = np.array(df['5'], int)
target

array([2, 2, 3, ..., 2, 1, 1])

In [14]:
from sklearn.metrics import accuracy_score as acc

acc(target, preds)

0.326078799249531

## LEMMATIZED

In [15]:
from pymystem3 import Mystem
import nltk
import re
mystem = Mystem() 

def nlp_process(text):
    tokens = nltk.word_tokenize(text)
    clear_tokens = []
    for token in tokens:
        new_token = re.sub(r'[^\w\s]', '', token)
        if new_token != '':
            new_token = mystem.lemmatize(token)
            clear_tokens.append(new_token[0])
    return ' '.join(clear_tokens)

In [16]:
df_stemmed = df.copy()
names = ['0', '1', '2', '3', '4']

for name in names:
    df_stemmed[name] = [nlp_process(text) for text in df[name]]
df_stemmed

0  \
0       совещательный орган при император в начало XX в   
1     министр внутренний дело с 1904 г либерал автор...   
2     какой из называть событие происходить 27 январ...   
3     что из называть относиться к результат первый ...   
4     для выход из экономический кризис вызывать пер...   
5     творчество поэт гумилев ахматова мандельштам в...   
6      самый многочисленный сословие российский империя   
7     усиление позиция россия в китай вызывать в пер...   
8     какой из называть событие происходить рано другой   
9     отмечать о ком идти речь дворянин политический...   
10            аграрный реформа столыпин предусматривать   
11    какой из перечисленный событие первый мировой ...   
12    какой из перечисленный требование быть характе...   
13    кто из называть ученый являться создатель учен...   
14    название это направление в поэзия происходить ...   
15    самый экономически могущественный класс россий...   
16    кто из называть государственный деятель быть с...   
17    командующий русский сухопутный армия в русско ...   
18    слово вы нужный великий потрясение мы нужный в...   
19    что из называть быть один из цель россия в пер...   
20    за немедленный заключение демократический мир ...   
21    отмечать знаменитый актер немой кино начинать ...   
22                  в какой ряд называть поэт символист   
23    по инициатива начальник московский охранный от...   
24    требование подготовка и осуществление пролетар...   
25    что из называть быть один из причина революция...   
26    участок земля выделять крестьянин при выход из...   
27    какой из называть событие происходить 1 август...   
28    кто из называть русский художник конец XIX нач...   
29    в какой ряд перечислять имя талантливый кресть...   
...                                                 ...   
5300  какой из этот созвездие не принадлежать к созв...   
5301  на что быть согласный василий теркин в поэма а...   
5302        в какой город установленный памятник клизма   
5303          в какой вид спорт преуспевать марат сафин   
5304         как называться хоккейный клуб из питтсбург   
5305  какой животное упоминаться как в название кома...   
5306     какой современный город рано называться сайгон   
5307      в какой из этот страна латинский письменность   
5308      денежный единица вьетнам в колониальный эпоха   
5309       последний вьетнамский императорский династия   
5310                  самый населенный город во вьетнам   
5311  на территория какой современный государство бы...   
5312  что из нижеперечисленный не являться символ вь...   
5313  какой из этот название никогда не иметь отноше...   
5314               сколько длиться беременность у кошка   
5315                         популярный вьетнамский суп   
5316           какой факультет изначально не быть в мгу   
5317  самый древний университет на территория европа...   
5318  какой прозвище быть у жена брат президент нго ...   
5319     какой из этот писатель посадить за мужеловство   
5320                        кто такой мастерс и джонсон   
5321  какой музей объединять новый арбат и рамбло в ...   
5322        как с латынь переводиться слово диссертация   
5323  какой из этот часовой бренд основывать рано др...   
5324              какой фирма придумывать наручный часы   
5325          кто из этот деятель не быть президент сша   
5326  к какой династия принадлежать ричард львиный с...   
5327  что детская песня предлагать жевать на остров ...   
5328                  как называть острый мышечный боль   
5329           кто стремиться избавляться от свой хвост   

                                                      1  \
0                                                 сенат   
1                                         лорис меликов   
2              подрыв флагманский корабль петропавловск   
3                            появление многопартийность   
4       вводить 8 часовой рабочий день в промышленность   
5                                        

In [17]:
lst_df_lemm = df_stemmed.values.tolist()

In [18]:
from multiprocessing import Pool

p = Pool(6)

FT_embs_lemm = p.map(get_vec, lst_df_lemm)
FT_embs_lemm = np.array(FT_embs_lemm)

In [19]:
import pickle

with open('fasttext_embed_lemm3.pickle', 'wb') as f:
    pickle.dump(FT_embs_lemm, f)

In [20]:
from sklearn.metrics.pairwise import cosine_similarity as cos
cosines = np.zeros((FT_embs_lemm.shape[0], FT_embs_lemm.shape[1]-1))
cosines.shape

(5330, 4)

In [21]:
for i in range(len(df)):
    for j in range(1,5):
        cosines[i, j-1] = cos(FT_embs_lemm[i,0].reshape(1,-1), FT_embs_lemm[i,j].reshape(1,-1))[0]

In [22]:
cosines

array([[ 0.2049735 ,  0.19350092,  0.06790652,  0.21344542],
       [ 0.03459496,  0.17356271, -0.00959812,  0.09914419],
       [ 0.2023272 ,  0.35063089,  0.26119753,  0.13590529],
       ...,
       [ 0.31017261,  0.32570848,  0.35385786,  0.32570848],
       [ 0.37400792,  0.24187348,  0.25267692,  0.27424472],
       [ 0.18337317,  0.14563994,  0.18253171,  0.17495403]])

In [23]:
preds = np.argmax(cosines, axis=1)
preds = preds + 1
preds

array([4, 2, 2, ..., 3, 1, 1])

In [24]:
target = np.array(df['5'], int)
target

array([2, 2, 3, ..., 2, 1, 1])

In [25]:
from sklearn.metrics import accuracy_score as acc

acc(target, preds)

0.2885553470919325